Vagrant.configure("2") do |config|
  config.vm.box = "avf/ubuntu-24.04-arm64"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "examples", "/home/vagrant/examples", type: :avf_virtiofs

  config.vm.provider :avf do |avf|
    avf.guest = :linux
    avf.cpus = 4
    avf.memory_mb = 4096
    avf.disk_gb = 16
    avf.headless = true
  end
end
